### ISSUE TITLE
Global Headers for Requests

### ISSUE THREAD

**Issue by zhigang1992** [dreamhead/moco#102]
It would be nice to have a way to specify a global requirement for HTTP request headers, just like the response does.
```json
{
    "request": {
        "headers": {
          "token": "abc"
        }
    },
    "include": "services.json"
}
```
So that all the request must have a `token` field in their header, in order to get picked up by moco.

**Comment by dreamhead** [comment]
The global request matcher has been implemented in latest codebase. So you can build your own Moco jar to try this new feature.
