### ISSUE TITLE
Does Moco Standalone Support These Use Cases?

### ISSUE THREAD

**Issue by arnm** [dreamhead/moco#107]
## What I'm Trying to Mock

I'm trying to mock an endpoint with this format:

http://host.com/resources/{id}

A GET on http://host.com/resources/123 yields this:
``` JSON
{ "id": 123 }
```

### Use Case 1

I have downloaded the JSON and saved it to a file named "123.json" to "tests/resources/responses/get/resources/"

I would like to have something like this in the config file:
```JSON
{
        "request": {
            "method": "get",
            "uri": {
                "match": "/resources/.*"
            }
        },
        "response": {
            "file": {
                "template": "tests/resources/responses/get${req.uri}.json"
            }
        }
    }
```
Where "tests/resources/responses/get${req.uri}.json" would resolve to "tests/resources/responses/get/resources/123.json". Then the resulting file path would be used to respond with the file.

e.g:

GET http://host.com/resources/123 would return the content of the file
``` JSON
{ "id": 123 }
```

### Use Case 2

I have downloaded the JSON and saved it to a file named "123" (with no file extension) to "tests/resources/responses/get/resources/"

I would like to have something like this in the config file:

```JSON
{
        "mount": {
            "dir": "tests/resources/responses/get/resources",
            "uri": "/resources",
            "headers": {
                "content-type": "application/json"
            }
        }
    }
```

e.g:

GET http://host.com/resources/123 would return proper JSON (not just plain text because of the missing file extension)
``` JSON
{ "id": 123 }
```

### Features That I'm Suggesting

1. All templates should be able to support interpolation of variables like when responding with text
2. Mount API should allow for the specification of headers

### Questions

With the current implementation, is there any way I could achieve the desired results above?

**Comment by dreamhead** [comment]
Feature 2 has been implemented in latest codebase.

Feature 1 is same with #37 . I've already implemented Java API, but I haven't figure out good enough JSON API.

Currently, file with template means return content from template file.
```json
"response": {
    "file": {
        "template": "template_file"
    }
}
```

If I want to keep this, we have to design a different API.

One is the extension from name (this will be released in next release):
```json
"response": {
    "file": {
        "name": {
            "template" : "get${req.uri}.json"
        }
    }
}
```

The other is to give a different operator.
```json
"response": {
    "file": {
        "???": "get${req.uri}.json"
    }
}
```

template_name? I'm not sure. This is situation I'm suffering.

**Comment by dreamhead** [comment]
Here is feature which has been implemented in current code base.

```json
[
  {
    "response":
    {
      "file":
      {
        "name": {
          "template": {
            "with" : "src/test/resources/${var}.response",
            "vars" : {
              "var" : "foo"
            }
          }
        }
      }
    }
  }
]
```
