### ISSUE TITLE
Feature Request: Namespacing for stubbing multiple apps with one Moco instance

### ISSUE THREAD

**Issue by garrettheel** [dreamhead/moco#11]
I think it would be useful for Moco to allow multiple config files to be loaded into a single instance, each with a different namespace. 

This would avoid needing to spin up multiple instances of Moco when you want to run a few different stubs at the same time (for example during a build pipeline).

Here's a rough example of how this could work:

``` java
Runner runner = new NamespacedRunner(8080);
runner.addConfig("myApp1", "/path/to/myConfig1.json");
runner.addConfig("myApp2", "/path/to/myConfig2.json");
runner.run()
```

After doing this, the matchers in `myConfig1.json` will all be implicitly prepended with the path `myApp1`. 

E.g if `myConfig1.json` defines a matcher to catch all GET requests, it will catch requests to `localhost:8080/myApp1**`, but not `localhost:8080/somethingElse`.  

Do you agree that this would be a useful feature? I would be happy to help in implementation.

Thanks,
Garrett

**Comment by Neway6655** [comment]
Hi, this is a great approach and we need it as well, when would moco provide this? thanks!

**Comment by dreamhead** [comment]
This feature has been in Moco for a long time.

https://github.com/dreamhead/moco/blob/master/moco-doc/global-settings.md#context

**Comment by Neway6655** [comment]
got it, thanks
