### ISSUE TITLE
How can i get the client request url and parameter

### ISSUE THREAD

**Issue by henrysos** [dreamhead/moco#110]
ex: The browse send a post request
                       http://localhost/abc/ab 
      post body {"para1":1,"para2":2}

how can i use java api to get   /abc/ab  and  body content {"para1":1,"para2":2}

and how can i assert  path = /abc/ab and the post body={"para1":1,"para2":2}, 

thanks

**Comment by dreamhead** [comment]
If you want to setup your matcher, **uri** will help you get /abc/ab part, for your content, if you just care about json structure, **json** API will be your helper.

If you want to return content with uri and json, please read **template** API document.

**Comment by henrysos** [comment]
the post body is not only json,  it maybe string, i want to use api like this

server.request(and(by(uri("/abc/ab")),by("{\"para1\":1,\"para2\":2}")).response(with(text("ok")), header("Content-Type", "text/html"));
			
			server.request(and(by(uri("/abc/ab")),by("{\"para1\":2,\"para2\":3}")).response(with(text("fail")), header("Content-Type", "text/html"));

the api  only has the uri ,header ,but it  has not include body,so i don't know how to assert

**Comment by dreamhead** [comment]
Moco support [**verify**](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#verify) API which you may be interested in.
