### ISSUE TITLE
ERROR : Maven test fails to run moco server when using jacoco maven plugin.

### ISSUE THREAD

**Issue by aelaibi** [dreamhead/moco#111]
Hi,

I have used moco to mock a rest-json service , My test look like this :

 @Test
    public void should_return_expected_response() throws Exception {
        final HttpServer server = jsonHttpServer(12306, file("foo.json"));
        running(server, new Runnable() {
            @Override
            public void run() throws Exception {
                 Contrat contrat = contratClient.getContrat(numcontrat);
                Assert.assertNotNull(contrat);
            }
        });
    }
//contratClient is a service autowiring a RestTemplate client

When I run my test under intellij-idea, it works (with green as a result), but when I try to run it via maven (using mvn clean install) it fails with the exception :

java.lang.IllegalArgumentException: unknown configuration :[Z@d78df0

When I do the same (mvn clean install) with no breakpoints it passes and with success 

Do you have any idea to explain this stange behaviour ?

NB: I use windows 7, JDK 6, moco-runner V0.10.0, junit 4

**Comment by dreamhead** [comment]
Could you please provide your foo.json?

**Comment by aelaibi** [comment]
[
  {
    "request":{
      "uri":"/bancassurance/api/v1/contrats/",
      "queries":{
        "rib":"rib01"
      }
    },
    "response":{
      "headers":{
        "content-type":"application/json;charset=UTF-8"
      },
      "text":"[{\"numContrat\" : \"numcontrat01\", \"produit\" :\"AGE D'OR\", \"statut\":\"O\", \"dateEffet\":\"\"}]"
    }
  },
  {
    "request":{
      "uri":"/bancassurance/api/v1/contrats/numcontrat01"
    },
    "response":{
      "headers":{
        "content-type":"application/json;charset=UTF-8"
      },
      "text":"{\"numContrat\" : \"numcontrat01\", \"produit\" :\"\", \"statut\":\"\", \"dateEffet\":\"\"}"
    }
  },
  {
    "response":{
      "status" :"404",
      "headers":{
        "content-type":"application/json"
      }
    }
  }
]

**Comment by aelaibi** [comment]
I guess I found the cause, 

I'm using org.jacoco:jacoco-maven-plugin v : 0.6.0.201210061924

and it seems it adds somme $field.. that's cause problems to moco-runner.

When I upgrade the jacoco version to  0.7.2.201409121644, my moco test runs with success !

**Comment by dreamhead** [comment]
OK, good.

**Comment by marcingrzejszczak** [comment]
The issue is back with jacoco >= 0.7.8
