### ISSUE TITLE
How to use template in json and redirectTo?

### ISSUE THREAD

**Issue by luozhengjia** [dreamhead/moco#114]
For example, http://localhost:9090/abc?redirectUrl=http://www.baidu.com

**Comment by dreamhead** [comment]
No, only String is supported right now. Why do you think it is a good feature?

**Comment by luozhengjia** [comment]
本地开发环境中，多个开发者需要和微信平台通信,这个场景需要能从微信服务端302重定向回到开发者环境。
另外，moco现在的template写法的局限性太大了，为什么不能直接使用${}表示变量？

**Comment by dreamhead** [comment]
I think it could be easy to support template in redirectTo.

I'm not sure if what you need is custom variable in template.
https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#custom-variable

**Comment by dreamhead** [comment]
redirect template has been added into codebase which will be published at next release.
