### ISSUE TITLE
How to stop moco http server in terminal? 

### ISSUE THREAD

**Issue by sunqingquan** [dreamhead/moco#115]
HI dreamhead,
I can start moco http server in terminal on mac os with "ava -jar moco-runner-<version>-standalone.jar http -p 12306 -c foo.json", and  visit "http://localhost:12306" successfully.
but how to stop moco http server in terminal?

**Comment by dreamhead** [comment]
Ctrl-C

**Comment by sunqingquan** [comment]
Yes,ctrl-c can stop moco http server.
but I write a shell script to start moco server, I also want to stop moco server in this script and continue do other things.
what shoud I do?

**Comment by dreamhead** [comment]
You can use shutdown port to stop moco server.

https://github.com/dreamhead/moco/blob/master/moco-doc/cmd.md#shutdown
