### ISSUE TITLE
Could you please help me diagnose the reason why bootstrap fails?

### ISSUE THREAD

**Issue by xingyuemitu** [dreamhead/moco#116]
macdeMacBook-Pro:moco mac$ java -jar moco-runner-0.10.1-standalone.jar start -p 12306 -c test.json 
15 六月 2015 22:11:37 [main] INFO  Unrecognized field: Unrecognized field "name" (class com.github.dreamhead.moco.parser.model.RequestSetting), not marked as ignorable (14 known properties: "method", "headers", "queries", "json", "path_resource", "factory", "uri", "text", "cookies", "forms", "xpaths", "json_paths", "version", "file"])
 at [Source: java.io.InputStreamReader@58c1c010; line: 6, column: 17] (through reference chain: java.util.ArrayList[0]->com.github.dreamhead.moco.parser.model.SessionSetting["request"]->com.github.dreamhead.moco.parser.model.RequestSetting["name"])
15 六月 2015 22:11:37 [main] ERROR Unrecognized field [ name ], please check!

**Comment by dreamhead** [comment]
Moco fails to parse your configuration file. There is an unknown field whose name is 'name'.

**Comment by xingyuemitu** [comment]
Thank you
