### ISSUE TITLE
Proxy failed for request with compression enabled

### ISSUE THREAD

**Issue by zhigang1992** [dreamhead/moco#123]
HttpServer server = httpServer(12306, context("/"));
        server.get(match(uri("/repos/.*")))
                .response(proxy(from("/repos").to("https://api.github.com/repos"), playback("playback.response")));
        running(server, new Runnable() {
            @Override
            public void run() throws Exception {
                helper.getWithHeader("http://localhost:12306/repos/dreamhead/moco/contributors", of("Accept-Encoding", ""));
            }
        });

This passes and save responses to the file.
But

        HttpServer server = httpServer(12306, context("/"));
        server.get(match(uri("/repos/.*")))
                .response(proxy(from("/repos").to("https://api.github.com/repos"), playback("playback.response")));
        running(server, new Runnable() {
            @Override
            public void run() throws Exception {
                helper.get("http://localhost:12306/repos/HipByte/RubyMotion/contributors");
            }
        });

Didn't save anything

**Comment by dreamhead** [comment]
Thank you for your issue. 

It's definitely a bug related to chunked response. I've already committed a fix.
