### ISSUE TITLE
Support for query arrays?

### ISSUE THREAD

**Issue by zhigang1992** [dreamhead/moco#124]
Something like this
```
http://example.com/view?ids[]=1&ids[]=2
```
Although this is not a HTTP standar, but it's still widely used in a lot of popular projects.
Where is moco, we only take the first one.
https://github.com/dreamhead/moco/blob/cdfd6170292e04a6aed32f007c58afce38fe059a/moco-core/src/main/java/com/github/dreamhead/moco/model/DefaultHttpRequest.java#L152
Do we consider add support for this?

**Comment by dreamhead** [comment]
Yes, the support has been added which will be in next release.
