### ISSUE TITLE
HEAD request returns body

### ISSUE THREAD

**Issue by arnm** [dreamhead/moco#126]
Result are with latest version `0.10.1`

Why does a HEAD request yield a body?

```json
[
    {
        "request": {
            "uri": {
                "startsWith": "/prefix"
            }
        },
        "response": {
            "text": {
                "template": "${req}"
            },
            "headers": {
                "header": "1.0",
                "Date": "Mon, 02 Mar 2015 21:27:38 GMT"
            }
        }
    }
]
```

```
↳ curl -i -X HEAD http://localhost:5001/prefix
HTTP/1.1 200 OK
Date: Mon, 02 Mar 2015 21:27:38 GMT
Content-Length: 165
header: 1.0
Content-Type: text/plain; charset=UTF-8

HTTP Request{uri=/prefix, version=HTTP/1.1, method=HEAD, queries={}, headers={User-Agent=curl/7.37.1, Host=localhost:5001, Accept=*/*, Content-Length=0}, content=}%
```

**Comment by dreamhead** [comment]
You response content is set by your template.

```json
"text": {
    "template": "${req}"
}
```

```req``` is a template variable you can get request information.

**Comment by arnm** [comment]
I understand why it's happening but should it be?

Here is the [RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) on what HEAD is suppose to do:

<blockquote>
9.4 HEAD
<br /><br />
The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification.
</blockquote>

**Comment by dreamhead** [comment]
Good suggestion.

Currently, Moco sets response content based on your response setting, not your request.

**Comment by arnm** [comment]
After further thought, this probably shouldn't follow the spec to strictly. I can imaging someone trying to mock a server which did response with a body on a HEAD request. Making a change like this would not allow for that too easily. I'll close this as I think this is acceptable behavior.

**Comment by dreamhead** [comment]
Actually my recent change has implemented this feature which will be released in next release.

**Comment by arnm** [comment]
How will someone mock a server which does return a body in response to a HEAD request? Servers which do that are not following the HTTP spec but I have run into servers which do have this behavior. If this scenario can't be replicated I recommend this change not be made.

**Comment by dreamhead** [comment]
You're right. Not every programmer is a good programmer, especially in a tricky case.
