### ISSUE TITLE
Stubbing out binary content request

### ISSUE THREAD

**Issue by arnm** [dreamhead/moco#128]
How can a binary request be stubbed out?

I have a third party component which POSTs a form. The request's body ends up being the InputStream of a UTF-8 string (the url encoded form). How can I setup to stub this call?

**URL Encoded Form Body**
```
Action=asdf&Version=asfd
```

I'm currently trying to do it this way

```java
// Build form params
final List<NameValuePair> form = Lists.newArrayList();
form.add(new BasicNameValuePair("Action", "asdf"));
form.add(new BasicNameValuePair("Version", "asdf"));

// encode form params
final RequestMatcher requestMatcher = by(URLEncodedUtils.format(form, "UTF-8"));

// stub out any post calls with this body
server.post(requestMatcher).response(status(200))
```

**Moco Log of Request**
```
Request received:

POST / HTTP/1.1
Host: localhost:56780
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Content-Length: 2323
Connection: Keep-Alive

<content is binary>

Response return:

HTTP/1.1 400
```

**Comment by dreamhead** [comment]
Moco has already provide `form` API. Can you use it?

**Comment by arnm** [comment]
how can multiple form params be specified?

This is the example for a single param:
```java
server.post(eq(form("name"), "foo")).response("bar");
```

Could you provide an example of multiple params?

**Comment by arnm** [comment]
Everything works as expected. I was not stubbing out the correct request. Using both the Form API and using the standard request body both worked. The Form API automatically handles the URL encoding which is great. 

Multiple form params can be specified like so:
```java
server.post(and(eq(form("name"), "foo"), eq(form("name2"), "bar"))).response("bar");
```

It would be nice if this information was documented. Thanks
