### ISSUE TITLE
Timed sequence operator

### ISSUE THREAD

**Issue by schrepfler** [dreamhead/moco#129]
Provide sequence equivalent where it's possible to set a timed checkpoint from which the next element in the sequence is available.
```java
server.request(by(uri("/foo"))).response(seq("foo", "bar", "blah"));
```
hypothetical example where foo is available from the start, bar is available after 1000ms and blah after 5000ms but this can be completely different.
```java
server.request(by(uri("/foo"))).response(seq((0,"foo"), (1000,"bar"), (5000,"blah")));
```

**Comment by dreamhead** [comment]
You can do it. Moco has provided you a composite interface.

```java
server.request(by(uri("/foo"))).response(seq(and(with(latency(1000, TimeUnit.MILLISECONDS)), with(text("foo"))), and(with(latency(2000, TimeUnit.MILLISECONDS)), with(text("bar")))));
```

**Comment by schrepfler** [comment]
Moco is the best!
