### ISSUE TITLE
It seems Moco doesn't support Chinese Characters

### ISSUE THREAD

**Issue by KennyWZhang** [dreamhead/moco#133]
below is my configuration file.
![screen shot 2015-11-19 at 5 55 04 pm](https://cloud.githubusercontent.com/assets/1762105/11267496/b1d020ce-8ee6-11e5-83c5-18b6f3420df2.png)
and I could start moco server stub successfully.

However, when I try to request, i got a "?" in response.
![screen shot 2015-11-19 at 5 57 22 pm](https://cloud.githubusercontent.com/assets/1762105/11267567/035997cc-8ee7-11e5-9241-d7a6774b91ec.png)

**Comment by dreamhead** [comment]
I'm not quite sure which version you are using. I've tried your example with 0.10.2. It works well. My OS is mac.

**Comment by ios122** [comment]
我觉得,问题应该是JSON文件本身的编码,不是utf-8.windows下,手动更改下,应该就好了
