### ISSUE TITLE
Error:Client found response content type of 'text/xml,text/plain; charset=utf-8', but expected 'text/xml'.

### ISSUE THREAD

**Issue by karsen-clock** [dreamhead/moco#136]
I tried ,but failed.?

**Comment by dreamhead** [comment]
Moco supports any HTTP request and SOAP by default supports HTTP, so Moco can support SOAP request. But there is no SOAP specific API for now.

Could you please give me the example you've tried?

**Comment by karsen-clock** [comment]
misconfigured,,now I can get response text as expected. But have a new trouble.

config file as below:
[{
	"request": {
		"uri": "/corpinfomaintain/corpbaseinfo.asmx"
	},
	"response": {
		"latency": {
			"duration": 1,
			"unit": "second"
		},
		"headers" :
        {
          "content-type" : "text/xml"
        },
		"file": "test.response"
	}
}]

client give errors :+1: 

Exception:System.InvalidOperationException: Client found response content type of 'text/xml,text/plain; charset=utf-8', but expected 'text/xml'.&amp;#xD;&amp;#xA;T

**Comment by dreamhead** [comment]
Thank you for your report. It's Moco bug.

The reason why your Exception is your header is "content-type", but the default header for file is "Content-Type". A quick fix is to change your header to "Content-Type".

Http Header should be case-insensitive. so it's Moco bug. I'll fix it soon.

**Comment by karsen-clock** [comment]
but I have a workaround.   set 
			"content-type": "text/xml;charset=utf-8"
and replace my xml file "<" ans "&lt;".
