### ISSUE TITLE
MocoTestHelper cant found?

### ISSUE THREAD

**Issue by JennyHui** [dreamhead/moco#139]
maven pom :
        <dependency>
            <groupId>com.github.dreamhead</groupId>
            <artifactId>moco-core</artifactId>
            <version>0.10.2</version>
        </dependency>

**Comment by dreamhead** [comment]
No, you can not find MocoTestHelper, because it is used by Moco test.

**Comment by JennyHui** [comment]
ok~i get it~so we dont have to use it~

- - sorry just that doc demo confused me a little~thx for ur help :)

**Comment by dreamhead** [comment]
Sorry for misleading code and I've already removed it.
