### ISSUE TITLE
No response when running moco on a remote server

### ISSUE THREAD

**Issue by karsen-clock** [dreamhead/moco#148]
I am running moco on a remote server and moco will be start by  remote CMD commands.

eg:
CMD/C java -jar D:/GitLocal/CorpPlatform/src/mock/static/globalconfig/moco-runner-0.10.2-standalone.jar http -p 12306 -gD:/GitLocal/CorpPlatform/src/mock/static/globalconfig/api.json

But waiting without any  response,If I login the remote server ,and execute cmd manually ,I can get response immediately.

netstat on the server :
 TCP    0.0.0.0:12306          0.0.0.0:0              LISTENING       6540
 TCP    10.2.8.27:12306        172.0.0.173:55760   ESTABLISHED     6540
 TCP    10.2.8.27:12306        172.0.0.173:55761   ESTABLISHED     6540

Could you please give me some suggestions?

**Comment by dreamhead** [comment]
Have you ever checked your network configuration? e.g. firewall.

**Comment by karsen-clock** [comment]
I think this has nothing to do with the network.I run moco manually,but request from my client,


the only difference is how I start moco command, start by web server ,without any response just waiting and no error message.  login the remote server start moco, and send request from my client works well.
I doubt maybe it's matters with Authorization?
the web server running on a server 2008+Apache+django

**Comment by karsen-clock** [comment]
update config file during running... can't load config file... aother problem...
