### ISSUE TITLE
Use moco to proxy request with parameters

### ISSUE THREAD

**Issue by shane51** [dreamhead/moco#159]
I'm trying to use Moco proxy to enhance server stability.
But my server queries params such as:
```json
[
  {
    "request": {
       "uri" : {
                "match" : "/proxy/.*"
            },
      "queries" : {
        "q" : ".*"
      }
    },
    "response": {
      "proxy":
      {
        "from" : "/proxy",
        "to" : "https://api.github.com"
      }
    }
  }
]
```

I want to forward any value of query param( 'q' ) to Github api, for example,
if I request 
`http://localhost:3000?q=dreamhead`,
I hope moco proxy the request to real Github server as 
`https://api.github.com?q=dreamhead`

I tries several methods, it always show HTTP 400 error.

How does moco support this scenario?

**Comment by dreamhead** [comment]
Query with regular expression should be like this

```json
"queries": {
    "foo": {
        "match" : ".*"
    }
}
```

**Comment by shane51** [comment]
It works! thanks!

```json
[
  {
    "request": {
      "uri" : {
        "match" : "/.*"
        },
      "queries" : {
        "q" : {
          "match" : ".*"
          }
      }
    },
    "response": {
      "proxy":
      {
        "from" : "/",
        "to" : "https://api.github.com",
        "failover" : "failover.json"
      }
    }
  }
]

```
