### ISSUE TITLE
图形界面配置

### ISSUE THREAD

**Issue by zhuxiangzx** [dreamhead/moco#170]
能不能做一个页面来进行配置呢？这样在实际的工作中效率更高，更方便管理

**Comment by dreamhead** [comment]
I'm not a good UI developer. Could you please contribute one?

**Comment by zhuxiangzx** [comment]
@dreamhead 可以的，因为在实际的测试工作中就是在用您的moco ,没有方便的配置和管理界面真的是个痛

**Comment by dreamhead** [comment]
@zhuxiangzx Waiting for your contribution. :)
