### ISSUE TITLE
Can not start https on version 0.11.0

### ISSUE THREAD

**Issue by wangyunshuai** [dreamhead/moco#171]
Platform: Mac 10.12
java version：1.7.0_45

When I start moco server as below, server could start correctly.
`sudo java -jar /Users/smzdm/moco/moco.jar http -p 80 -c /Users/smzdm/moco/json/data_test.json`

But https server can not start normally:
`sudo java -jar /Users/smzdm/moco/moco.jar https -p 80 -c /Users/smzdm/moco/json/data_test.json`
Need I do some configuration for https?

Thank you.

**Comment by dreamhead** [comment]
Refer to [Moco HTTPS](https://github.com/dreamhead/moco/blob/master/moco-doc/usage.md#https)

You need to provide more arguments to HTTPS.

**Comment by wangyunshuai** [comment]
@dreamhead Thank you.
