### ISSUE TITLE
Verify over HTTP

### ISSUE THREAD

**Issue by tyx** [dreamhead/moco#174]
Any chance you have plan to add something like `verify` over HTTP ? 

The idea would be to ensure that moco was called for a specific request.

**Comment by dreamhead** [comment]
Do you mean this `verify`?
https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#verify

**Comment by tyx** [comment]
Yes !

**Comment by tyx** [comment]
Not sure to get why you closed ? 
Currently `verify` is only for java api isn't it ? We need it for standalone. I guess I'm I misspoke

**Comment by dreamhead** [comment]
I thought your issue has been solved.

`verify` is only for test scenario, which is just like `verify` in mock framework. But a standalone server is setup as a server, not a test.

**Comment by tyx** [comment]
Yep but I guess many of us use the standalone server as test as we don't use java.

At least we do, and we are very happy with moco :+1: but we miss just the ability to ensure moco was called for some test. Just like mockbin for example : http://mockbin.com/docs#bin-access-log
