### ISSUE TITLE
Shouldn't DefaultRequestHit be thread-safe?

### ISSUE THREAD

**Issue by andredasilvapinto** [dreamhead/moco#178]
So we know that verify will always return true after onMessageArrived was called with the right request, independently of what threads are calling it?

**Comment by dreamhead** [comment]
No, the current DefaultRequestHit is not implemented for thread-safe, but it is not by design. 

Please feel free to change it and make a PR.

**Comment by dreamhead** [comment]
This feature will be at the next release.

You can checkout latest code if you need it for now.
