### ISSUE TITLE
Does not support empty query parameter

### ISSUE THREAD

**Issue by MountLion** [dreamhead/moco#181]
When mock this query : 
`http://.../item?new`
using the following config:
<pre>
[
   {
     "request" :
       {
         "uri" : "/item",
         "queries" : {
             "new" : ""
         }
       },
     "response" :
       {
         "text" : "ok"
       }
   }
]
</pre>
moco failed to startup:
`ERROR java.lang.IllegalArgumentException: Expected content should not be null`

**Comment by macdao** [comment]
I think the feature was implemented in @1302d4449b86840834c430f94504d2e788d9780b

**Comment by dreamhead** [comment]
@macdao Thank you for your reply.

@MountLion if you need it, try to build from latest source until latest Moco is released.
