### ISSUE TITLE
Can not support multiple query parameters

### ISSUE THREAD

**Issue by lynic** [dreamhead/moco#184]
I use following uri to mach my request:

```json
{
   "uri": "/aaa",
   "queries": {
     "a": "aa",
     "b": "bb"
  }
}
```
But it didn't match my request to /aaa?a=aa&b=bb

**Comment by lynic** [comment]
But if I use

> {
> "uri": "/aaa"
> "queries": {
> "a": "aa"
> }
> }

It matches my request to /aaa?a=aa&b=bb , it's weird.

**Comment by dreamhead** [comment]
Refer to this configuration
https://github.com/dreamhead/moco/blob/master/moco-runner/src/test/resources/query.json

And should_return_expected_response_based_on_specified_multi_query_request in
https://github.com/dreamhead/moco/blob/master/moco-runner/src/test/java/com/github/dreamhead/moco/MocoStandaloneTest.java

**Comment by lynic** [comment]
Thanks for giving the example, what is the minimal version of moco should I use to enable this feature?

**Comment by dreamhead** [comment]
Try the latest version if you need my advice. :)
