### ISSUE TITLE
cannot support JSON in GBK

### ISSUE THREAD

**Issue by macdao** [dreamhead/moco#191]
I have to mock a legacy system which use JSON with GBK.

Right now Moco matches JSON using `byte[]` directly:

```java
    private boolean doMatch(final Request request, final byte[] content) {
        try {
            JsonNode requestNode = mapper.readTree(content);
            JsonNode resourceNode = mapper.readTree(expected.readFor(of(request)).getContent());
            return requestNode.equals(resourceNode);
        } catch (JsonProcessingException jpe) {
            return false;
        } catch (IOException e) {
            throw new MocoException(e);
        }
    }
```

The ObjectMapper always use Unicode see `ByteSourceJsonBootstrapper.detectEncoding`.

I know that the standard JSON is Unicode, but you know there's many legacy system :(

Previously I use 0.10.2 which can support GBK JSON with `-Dfile.encoding=GBK` options.

The  related commit is @26c6f8dd55274e73cc117bc1a110fc76ddf0aeb2

**Comment by dreamhead** [comment]
Could you please provide a test case for this?

**Comment by macdao** [comment]
you mean unit test for junit or a readable test case for human?

**Comment by dreamhead** [comment]
Unit test is a better choice.

**Comment by dreamhead** [comment]
Unit test has been added. Thank you for your contribution.

**Comment by dreamhead** [comment]
Check unit tests: should_match_request_with_gbk_resource and should_match_gbk_request in https://github.com/dreamhead/moco/blob/master/moco-core/src/test/java/com/github/dreamhead/moco/MocoJsonTest.java

Get request charset to pass should_match_gbk_request in commit https://github.com/dreamhead/moco/commit/7d8fca621f453f2cd48b209ea2743db23661775e

**Comment by macdao** [comment]
Cool
