### ISSUE TITLE
moco能转发请求吗

### ISSUE THREAD

**Issue by testsw4** [dreamhead/moco#217]
moco了一个借口,但是要向回调地址传数据,要怎么写

**Comment by dreamhead** [comment]
Try [Event](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#event)

**Comment by testsw4** [comment]
{
    "request": {
        "uri" : "/event"
    },
    "response": {
        "text": "event"
    },
    "on": {
        "complete": {
            "post" : {
                "url" : "http://another_site",
                "content": "content"
            }
        }
    }
}

试过了,但是我现在要把"content": "content",把"content"写成json格式,好像不能

**Comment by dreamhead** [comment]
Currently JSON is supported here.
