### ISSUE TITLE
Moco 可以监听非localhost请求吗？

### ISSUE THREAD

**Issue by IAmFQQ** [dreamhead/moco#219]
host = "localhost";
    	port = 8808;
    	address = "http://"+host+":"+port;
    	
        HttpServer server = jsonHttpServer(port, file("src/test/resources/server.json"));
        runner = runner(server);
        runner.start();
一般是这么做来启动一个mock server 用来捕获8808的请求，请问moco可以监听非localhost的endpoint，
比如说www.alipay.com

**Comment by dreamhead** [comment]
You can try `proxy` to create alipay proxy with [batch URLs](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#batch-urls)

```java
server.request(match(uri("/proxy/.*")))
    .response(proxy(from("/proxy").to("http://alipay.com")));
```

**Comment by IAmFQQ** [comment]
@dreamhead Thank you!
