### ISSUE TITLE
Could you delete this limit "Status Code must be greater than zero" ? 

### ISSUE THREAD

**Issue by yaitza** [dreamhead/moco#221]
Could you delete this limit "Status Code must be greater than zero" ? 
Because the status code include 00，10，20 and so on。this status code always be defined by the coder.

**Comment by dreamhead** [comment]
Status code is the HTTP status code which has specific meaning in its context.

I can understand your design to use status code for your business case, but I don't think it is a good idea based on my personal experience.

**Comment by yaitza** [comment]
OK， I see.
