### ISSUE TITLE
response in json , template it does not effective

### ISSUE THREAD

**Issue by kingkongge** [dreamhead/moco#243]
**moco version： moco-runner-0.12.0-standalone.jar**

- json:

_mock_ file content : 
![image](https://user-images.githubusercontent.com/3470123/42746241-7ba51e9e-8909-11e8-84ea-e703d2a8729d.png)

mock _result:_
![image](https://user-images.githubusercontent.com/3470123/42746514-afd79484-890a-11e8-9d83-b921f8351eb2.png)

====================================================
if  response in text, template is ok
- text:

mock file content : __
![image](https://user-images.githubusercontent.com/3470123/42746523-bffaa7ac-890a-11e8-91d3-b1359f70a91e.png)

mock _result:_
![image](https://user-images.githubusercontent.com/3470123/42746538-d147a2c6-890a-11e8-9325-0e121b7a32b4.png)

====================================================
my app need json response , and i need different req.uri to proxy different real uri 
how to config template funtion in json response
3ks

**Comment by hejinwei** [comment]
+1

**Comment by kingkongge** [comment]
![image](https://user-images.githubusercontent.com/3470123/49277022-392b4980-f4bb-11e8-9588-59742e23d5b4.png)

This configuration can solve my problem.
