### ISSUE TITLE
json param is random 

### ISSUE THREAD

**Issue by 15652915156** [dreamhead/moco#256]
request params
```json
"json": {
"a": "1",
"b": 2
}
```
but the value "b" is random ,how match it，it seems json need full match

**Comment by 15652915156** [comment]
@dreamhead can you help to answer this problem？thanks！

**Comment by dreamhead** [comment]
You can try [`jsonPath`](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#jsonpath)

**Comment by 15652915156** [comment]
Thanks for your kindly help.
