### ISSUE TITLE
Could you show me the architecture of moco?

### ISSUE THREAD

**Issue by waitshang** [dreamhead/moco#257]
I want to know more about moco and its design pattern. Could you help me.

**Comment by dreamhead** [comment]
The basic idea of Moco is very simple: RequestMatcher and ResponseHandler. If your request matches any matcher, the corresponding response handler will be invoked to return response.

**Comment by dreamhead** [comment]
@waitshang I wrote a Chinese article about Moco design. I hope it is helpful.
