### ISSUE TITLE
使用异步功能时，怎样指定访问第三方url的headers？

### ISSUE THREAD

**Issue by thz1018** [dreamhead/moco#261]
"on": {
                    
            "complete": {
            "async" : "true",
            "latency": {
                  "duration": 3,
                  "unit": "second"
              },

            "post" : {
                  "url" : "url_test",
                  "content":{  "template":"template"}
                     }
              }
}
访问url_test时默认使用text/plain格式，怎样配置能达到使用指定的headers？

**Comment by dreamhead** [comment]
The latest codebase has supported post event with headers.

https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#post-request

**Comment by dreamhead** [comment]
1.0.0 has been released which includes this feature.
