### ISSUE TITLE
post error

### ISSUE THREAD

**Issue by suxuliaoyuan** [dreamhead/moco#264]
![image](https://user-images.githubusercontent.com/55732743/65691079-d2f36100-e0a2-11e9-814f-43005ac2fc5d.png)
![image](https://user-images.githubusercontent.com/55732743/65691096-d8e94200-e0a2-11e9-8fcf-500e49f64b79.png)
![image](https://user-images.githubusercontent.com/55732743/65691127-e43c6d80-e0a2-11e9-90e5-4f7387dd412c.png)
I don't know where is the error?

**Comment by dreamhead** [comment]
It works for x-www-form-urlencoded. I'll try to figure out what's wrong for form-data.

**Comment by dreamhead** [comment]
It works for `form-data` as well for the latest codebase. Maybe it related to Netty implementation since I've already upgraded Netty to latest version in codebase.

Try to build your own Moco
```bash
./gradlew proguard
```

And the latest Moco will be found in
`moco-runner/build/libs/moco-runner-<version>-standalone.jar`

**Comment by suxuliaoyuan** [comment]
Thank you very much for your help！！！
