### ISSUE TITLE
我自己启动了moco，但是发现回包太快了，可不可以设置一下回包延时？

### ISSUE THREAD

**Issue by liuxp988** [dreamhead/moco#271]
我自己启动了moco，但是发现回包太快了，可不可以设置一下回包延时？用来测试一些等待操作或回包超时的场景

**Comment by dreamhead** [comment]
What you need is [latency](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#latency)

**Comment by liuxp988** [comment]
Thank you very much!
