### ISSUE TITLE
Seems incorrect example of "exist operator" in "HTTP APIs" doc.

### ISSUE THREAD

**Issue by lyscu** [dreamhead/moco#273]
in "Exist operator" chapter,  _**"foo": {"exist" : "not"}**_ is found. But actually, if set as described, error will be found in log. **_"ERROR java.lang.IllegalArgumentException: Unknown exist parameter: [not]"_**
After I change "_**not**_" to "**_false_**", then it works as expected.

**Comment by dreamhead** [comment]
Thank you for your correction. I've fix it.
