### ISSUE TITLE
[Release] No tag for 1.1.0 release and Version is not updated to next development version

### ISSUE THREAD

**Issue by NancyChunlan** [dreamhead/moco#293]
Hi, @dreamhead 

Moco 1.1.0 is released, but no tag found. 
And the version in build.gradle is not updated to next development version, it may lead 1.1.0 release to be overridden in mistake.
Would  you mind to check this? Thanks!

**Comment by dreamhead** [comment]
The missing tag is added.

https://github.com/dreamhead/moco/tree/v0.11.0
