### ISSUE TITLE
Response map to local file

### ISSUE THREAD

**Issue by wuzhenli** [dreamhead/moco#297]
In configuration file , I need to write a lot of json text as respons. 
```[
  {
     "request" :
       {
        "method" : "get",
        "uri" : "/get"
       },
     "response" :
       {
        "text" : "{\"key1\":\"value1\",\"key2\":\"value2\" ...... }"
       }
  }
]
```
It's very inconvenient. How use local json file  as response?

**Comment by dreamhead** [comment]
What you need is the `file` api.

https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#content-1
