### ISSUE TITLE
How to define the regex for the json input. When I try it gives me an 400 Bad Request 

### ISSUE THREAD

**Issue by vinodronad** [dreamhead/moco#298]
Json input file.
 {
    "request": {
      "uri": "/api/v1/refresh/account",
      "method": "POST",
	  "headers": {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": {
        	"startsWith": "Bearer "
        },
        "SourceSystemId": "AAA",
        "SourceServerId": "BBB",
        "trackingId": {
        	"match": ".*"
        },
        "timestamp": {
        	"match": ".*"
        }
      },
      **"json": {
      	"accountNumber": {
      		"startsWith": "[0-9]"
      	}
      }**
    },
    "response": {
      "text":"{\"message\":\"Refresh request was sent to queue for processing\",\"refreshStatus\":\"OK\"}"
    }
  }

When I do not define any regex for the accountNumber and just use it as below it works
"json": {
      	"accountNumber": "981239812390123"
      }
Please help me out here!.

**Comment by tian-pengfei** [comment]
it doesnt support for json of request

**Comment by vinodronad** [comment]
Thank you for reply
