### ISSUE TITLE
如何获取URI中的子串值作为返回报文

### ISSUE THREAD

**Issue by iamxiaoguizi** [dreamhead/moco#314]
比如uri=/gw/AA/charge，这个AA是动态的
response中的mode字段取AA返回

**Comment by ComeonBug** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by dreamhead** [comment]
@iamxiaoguizi Moco uses freemarker as template engine, you can checkout freemark built-in string function.
https://freemarker.apache.org/docs/ref_builtins_string.html

**Comment by iamxiaoguizi** [comment]
使用freemarker可以了，原来还有这么多函数，非常强大的功能。非常感谢
