### ISSUE TITLE
default if json.req.prop not available

### ISSUE THREAD

**Issue by lvijay** [dreamhead/moco#320]
Hi, big fan of moco.

In my responses I often use `${req.json.cust_property}`.  But sometimes the property `cust_property` isn't sent in the request.  I would like to use a custom value in these cases.  Is such a feature available in moco?

If there isn't, may I propose something like `${req.jsonGetOrDefault("a.b", "42")}`?

**Comment by dreamhead** [comment]
Try this
```
${(req.json.cust_property)!"42"}
```
