### ISSUE TITLE
Use URI path parameters on the response template 

### ISSUE THREAD

**Issue by wapcrazut** [dreamhead/moco#325]
Is it possible to use URL parameters in path and insert them in the response template, as URL queries?

For some mocks, I see the need to insert values coming from the URL path.

For example:
- URI: `/v1/test/.*/example`
- Request: GET `/v1/test/dummy/example`
- Response: `dummy`

Maybe something like the following:

````
    {
        "request": {
            "uri": {
                "match": "/v1/test/.*/example"
            },
            "method": "get",
        },
        "response": {
            "status": 200,
            "text": {
                "template": "{$req.uri.param[0]}"
            },
            "headers": {
                "Content-Type": "application/json"
            }
        }
    },
````
Thanks.

**Comment by wapcrazut** [comment]
Hello @dreamhead, sorry to ping but I was wondering if you could have any idea if this is already implemented or if this needs some work. If that's the case, could you point me to where to start at? Thanks.

**Comment by dreamhead** [comment]
This feature is not supported for now.

I do want to implement this feature, that's like Spring RequestMapping parsing, as following:

```json
{
        "request": {
            "uri": {
                "path": "/v1/test/{foo-id}/example"
            },
            "method": "get",
        },
        "response": {
            "status": 200,
            "text": {
                "template": "{$req.uri.path.foo-id}"
            },
            "headers": {
                "Content-Type": "application/json"
            }
        }
}
```

**Comment by wapcrazut** [comment]
@dreamhead That seems pretty good, do you have plans on when to implement this? I would like to help but I'll need some guidance on how to extend Moco's functionality.

**Comment by dreamhead** [comment]
@wapcrazut Feel free to commit PR. I'll help you extend Moco.

**Comment by dreamhead** [comment]
@wapcrazut Your feature request has been included in release 1.4.0.
https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#path-2

**Comment by ComeonBug** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wapcrazut** [comment]
@dreamhead Awesome!! many thanks for the hard work you guys put into this project 🚀
