### ISSUE TITLE
返回值类型不支持xml

### ISSUE THREAD

**Issue by xiao-peng-yu** [dreamhead/moco#326]
![image](https://user-images.githubusercontent.com/68453850/211440812-fa50a031-3fd0-481a-91e5-7309beb586e4.png)
[
  {
  	"request" :
	{
		"uri":"/test",
		"method":"post"
	},
    "response" :
      {
        "text" : "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><service></service>"
      }
  }
]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><service></service>

**Comment by HelloEason** [comment]
use python lib json to fix it , copy the result to json file
```python
import json
xml_in_json = json.dumps(xml_body)
print(xml_in_json)
```
