### ISSUE TITLE
加载配置文件无法使用*.json

### ISSUE THREAD

**Issue by charming-cc** [dreamhead/moco#339]
10 10月 2023 10:52:30 [main] INFO  Unrecognized field: Unrecognized field "include" (class com.github.dreamhead.moco.parser.model.SessionSetting), not marked as ignorable (8 known properties: "response", "redirectTo", "mount", "proxy", "request", "websocket", "on", "resource"])
 at [Source: (String)"[
    {"include": "*.json"}
]"; line: 2, column: 18] (through reference chain: java.util.ArrayList[0]->com.github.dreamhead.moco.parser.model.SessionSetting["include"])
10 10月 2023 10:52:30 [main] ERROR Unrecognized field [ include ], please check!

**Comment by charming-cc** [comment]
<img width="1104" alt="image" src="https://github.com/dreamhead/moco/assets/73381532/117992bf-a85c-44b6-b537-7b7457a5e268">

**Comment by dreamhead** [comment]
You should use `-g` option.

```bash
java -jar moco-runner-<version>-standalone.jar http -p 12306 -g settings.json
```

**Comment by charming-cc** [comment]
<img width="1207" alt="image" src="https://github.com/dreamhead/moco/assets/73381532/8d813cb8-1b4c-4ca8-a057-b531c3e0862a">
还是一样的，当我的配置文件中指定了文件名，就不会出现这错误

**Comment by dreamhead** [comment]
I figure out what's wrong: you put global setting and configuration files in same directory. Moco loads global setting file as configuration file.

The simple solution is to put configuration file in separated directory, e.g foo:
```json
[
  {
    "include": "foo/*.json"
  }
]
```

**Comment by charming-cc** [comment]
The problem has been solved，thanks
