### ISSUE TITLE
The json in the configuration request needs to match all the json in the body in order for the test to pass

### ISSUE THREAD

**Issue by lqz2012** [dreamhead/moco#343]
When configured as queries parameter, only the parameters in the configuration need to be matched when calling, and the test can pass.
config: [{"request":{"uri":"/test","queries":{"key":"test1"}},"response":{"text":"success"}}]
test:  curl http://ip:12305/test?key=test1&name=a

When configured as a json parameter, all parameters in the body json need to be matched when calling to pass the test, otherwise the test will not pass.
config:  [{"request":{"uri":"/test","json":{"key":"test1"}},"response":{"text":"success"}}]

test1,  pass
curl -X POST http://ip:12305/test -H "Content-type: application/json" -d'
{
    "key": "test1"
}
'

test2,  fail
curl -X POST http://ip:12305/test -H "Content-type: application/json" -d'
{
    "key": "test1",
    "name": "a"
}
'

How can I make json parameters like queries parameters and pass the test only if they match the parameters in the configuration?

**Comment by dreamhead** [comment]
[`struct`](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#json-struct) allows you to match a JSON request only for same struct no matter what actual content is.

[`jsonPath`](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#jsonpath) allows you to match request with JSONPath.

**Comment by lqz2012** [comment]
> [`struct`](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#json-struct) allows you to match a JSON request only for same struct no matter what actual content is.
> 
> [`jsonPath`](https://github.com/dreamhead/moco/blob/master/moco-doc/apis.md#jsonpath) allows you to match request with JSONPath.


Yes, JSONPath can solve this problem, thank you very much

**Comment by ComeonBug** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
