### ISSUE TITLE
moco encodes the resposne text by default charset, how can I force it to use utf8? 

### ISSUE THREAD

**Issue by ratlsun** [dreamhead/moco#43]
It seems moco encodes the resposne text by default charset. How can I force it to use utf8?

**Comment by dreamhead** [comment]
@ratlsun I found a encoding bug in Moco, which is related to response. Moco uses byte array as interface, but in the implementation, it converts byte array to string which could lose encoding information. I've already rewritten this part to fix that. Check out the latest code. This fix will be in next release.

**Comment by KennyWZhang** [comment]
Today I also encountered this problem by v0.10.2 standalone jar, so I submitted a new issue #133.
