### ISSUE TITLE
Can it be used as a simulator for performance test

### ISSUE THREAD

**Issue by Neway6655** [dreamhead/moco#71]
We used moco in our functional test, and it really works well there, and further more, we want to used it in our performance test, as a simulator, what it is used is to mock a webservice, by receiving the specific request matching via xpath, and return a sample xml response.
Here is the code snippet: 
server.post(eq(xpath("//*[local-name()='userId']/text()"), "user-id")).response(with(pathResource("data/sampler_response.xml")), header("Content-Type", "text/xml"));

And if this is possible for performance test, the next step we wanted is to use the latency feature in the mock server, to simulate the behavior that mock server can return the response with some latency delay, is this also possible to be used in performance test?

**Comment by jjggww2002** [comment]
I am trying to use moco for performance testing and find an issued. Let take a look at a simple exo ample. If I use JMeter to send a simple request to moco server ,the response message is received after the specified latency time (1 second) correctly. If I set the cocurrent thread to 10 for JMeter , it will take about 1 to 2 seconds to get the response message. If the count of cocurrent thread is larger , the actual latency will be larger. Does anyone has any idea?
